spring.application.name=shop_backend

spring.datasource.url=jdbc:postgresql://localhost:5432/shop
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

app.currency-code=FCFA
app.upload-dir=uploads

jwt.expiration=86400000
jwt.secret=${JWT_SECRET:32323232323232323232323232323232323232323232}

#logging.level.org.springframework.web=DEBUG